export enum ConfigEnum {
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_DATABASE = 'DB_DATABASE',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_SYNC = 'DB_SYNC',
  MONGO_HOST = 'MONGO_HOST',
  MONGO_PORT = 'MONGO_PORT',
  MONGO_INITDB_DATABASE = 'MONGO_INITDB_DATABASE',
  MONGO_INITDB_USERNAME = 'MONGO_INITDB_USERNAME',
  MONGO_INITDB_PASSWORD = 'MONGO_INITDB_PASSWORD',
}
